[package]
name = "rust-microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.0", features = ["sqlite", "r2d2"] }
dotenv = "0.15"
r2d2 = "0.8"